# Generated by Django 5.2.6 on 2025-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'thread',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadMessages',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'thread_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
