# Generated by Django 5.2.6 on 2025-10-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal_assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadMessages',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
