# Generated by Django 6.0.5 on 2026-06-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreadMessages',
            new_name='ThreadMessage',
        ),
    ]
