/* eslint-disable */
/**
 * AUTO-GENERATED by `@neylonai/sdk` generate-sections.
 * Do not edit by hand — re-run after updating your website sections.
 */
import { observePageSection } from "@neylonai/sdk";

export const neylonSectionKeys = {
  "/": [
    "home-overview",
  ],
  "/about": [
    "about-hruthik-m",
  ],
  "/contact": [
    "contact-information",
  ],
  "/experience": [
    "professional-experience",
  ],
  "/projects": [
    "selected-projects",
  ],
  "/services": [
    "services-offered",
  ],
} as const;

export type NeylonPagePath = keyof typeof neylonSectionKeys;
export type NeylonSectionKey<P extends NeylonPagePath> =
  (typeof neylonSectionKeys)[P][number];

/**
 * Observe a section element. TypeScript only accepts keys that belong to the
 * given page path. The SDK handles visibility, dwell, and section registration
 * automatically the first time a path is observed.
 */
export function observeNeylonSection<P extends NeylonPagePath>(
  element: Element,
  input: {
    pagePath: P;
    sectionKey: NeylonSectionKey<P>;
    sectionLabel?: string;
    dwellMs?: number;
  },
): () => void {
  return observePageSection(element, input.sectionKey, {
    pagePath: input.pagePath,
    sectionLabel: input.sectionLabel,
    dwellMs: input.dwellMs,
  });
}
