export type PageSectionKeyManifest = Record<string, string[]>;

function escapeStringLiteral(value: string): string {
  return JSON.stringify(value);
}

/**
 * Renders a deterministic TypeScript module from a path-scoped section-key
 * manifest. Paths and keys are sorted so regeneration only diffs when the
 * sections actually change.
 */
export function renderSectionTypesModule(
  pages: PageSectionKeyManifest,
): string {
  const normalized: PageSectionKeyManifest = {};
  for (const path of Object.keys(pages).sort()) {
    const keys = [
      ...new Set(
        (pages[path] ?? [])
          .map((key) => key.trim())
          .filter(Boolean),
      ),
    ].sort();
    if (keys.length) normalized[path] = keys;
  }

  const entries = Object.entries(normalized)
    .map(([path, keys]) => {
      const list = keys.map((key) => `    ${escapeStringLiteral(key)},`).join("\n");
      return `  ${escapeStringLiteral(path)}: [\n${list}\n  ],`;
    })
    .join("\n");

  return `/* eslint-disable */
/**
 * AUTO-GENERATED by \`@neylonai/sdk\` generate-sections.
 * Do not edit by hand — re-run after website sections change.
 */
import { observePageSection } from "@neylonai/sdk";

export const neylonSectionKeys = {${
    entries ? `\n${entries}\n` : ""
  }} as const;

export type NeylonPagePath = keyof typeof neylonSectionKeys;
export type NeylonSectionKey<P extends NeylonPagePath> =
  (typeof neylonSectionKeys)[P][number];

/**
 * Observe a section element. TypeScript only accepts keys that belong to the
 * given page path. The SDK handles visibility, dwell, and section registration
 * automatically the first time a path is observed.
 */
export function observeNeylonSection<P extends NeylonPagePath>(
  element: Element,
  input: {
    pagePath: P;
    sectionKey: NeylonSectionKey<P>;
    sectionLabel?: string;
    dwellMs?: number;
  },
): () => void {
  return observePageSection(element, input.sectionKey, {
    pagePath: input.pagePath,
    sectionLabel: input.sectionLabel,
    dwellMs: input.dwellMs,
  });
}
`;
}
