name: CI/CD - Build & Deploy

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE: ${{ secrets.GCP_SERVICE_NAME }}
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.IMAGE_NAME }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Image
        run: |
          docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" .

      - name: Push Image
        run: |
          docker push "$IMAGE:${{ github.sha }}"
          docker push "$IMAGE:latest"

  # linter:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v6

  #     - name: Set up Python
  #       uses: actions/setup-python@v6
  #       with:
  #         python-version-file: ".python-version"
  #     # Consider using pre-commit.ci for open source project
  #     - name: Run pre-commit
  #       uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  # pytest:
  #   runs-on: ubuntu-latest

  #   services:
  #     redis:
  #       image: redis:7.2
  #       ports:
  #         - 6379:6379
  #     postgres:
  #       image: postgres:17
  #       ports:
  #         - 5432:5432
  #       env:
  #         POSTGRES_PASSWORD: postgres

  #   env:
  #     REDIS_URL: "redis://localhost:6379/0"
  #     # postgres://user:password@host:port/database
  #     DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v6

  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v8.1.0
  #       with:
  #         enable-cache: "true"

  #     - name: Set up Python
  #       uses: actions/setup-python@v6.2.0
  #       with:
  #         python-version-file: ".python-version"

  #     - name: Install dependencies
  #       run: uv sync --locked

  #     - name: Check DB Migrations
  #       run: uv run python manage.py makemigrations --check

  #     - name: Run DB Migrations
  #       run: uv run python manage.py migrate

  #     - name: Test with pytest
  #       run: uv run pytest
